services:
    app:
        container_name: 'drsamiraronaghi.com'
        image: "drsamiraronaghi.com"
        build:
            context: .
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '8000:8000'
            - '3000:3000'
        networks:
            - default

networks:
    default:
        external: true
        name: hidevs
